CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    first_name VARCHAR(100) NOT NULL DEFAULT '',
    last_name VARCHAR(100) NOT NULL DEFAULT '',
    password VARCHAR(255) NOT NULL,
    user_active INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (
    email,
    first_name,
    last_name,
    password,
    user_active
)
VALUES (
    'admin@example.com',
    'Admin',
    'User',
    '$2a$12$J9d9dQebBdl612sNdWl.BeWSbTVrnsXHy.F/DdpduY/r8eLBO6vd6',
    1
)
ON CONFLICT (email) DO UPDATE
SET
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    password = EXCLUDED.password,
    user_active = EXCLUDED.user_active,
    updated_at = CURRENT_TIMESTAMP;

